{
 "title": "Prover Observability",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Lastest Proven Id",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prover_latestProven_id{job=\"prover\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Verified Id",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prover_latestVerified_id{job=\"prover\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proof Generation Latency (In Seconds)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prover_proof_generation_time{job=\"prover\"} / 1000000000",
     "legendFormat": "P{{quantile}}"
    }
   ]
  },
  {
   "title": "Proof Generation Trend (In Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "prover_proof_generation_time{job=\"prover\"} / 1000000000",
     "legendFormat": "P{{quantile}}"
    }
   ]
  },
  {
   "title": "Proofs - Assigned/Requested",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "prover_proof_assigned{job=\"prover\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Valid Proofs - Generated",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "prover_proof_valid_received{job=\"prover\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Valid Proofs - Sent",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "prover_proof_valid_sent{job=\"prover\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}